cell_type_mapping = {
    'CD34-positive, CD56-positive, CD117-positive common innate lymphoid precursor, human': 'stem cell',
    'mesenchymal stem cell': 'stem cell',
    'CD4-positive helper T cell': 'T cell',
    'cortical thymic epithelial cell': 'thymic epithelial cell',
    'kidney loop of Henle thin descending limb epithelial cell': 'kidney epithelial cell',
    'CD8-alpha-beta-positive, alpha-beta intraepithelial T cell': 'T cell',
    'B cell': 'B cell',
    'paneth cell of colon': 'epithelial cell',
    'smooth muscle myoblast': 'muscle cell',
    'epithelial cell of lung': 'epithelial cell',
    'kidney loop of Henle thin ascending limb epithelial cell': 'kidney epithelial cell',
    'type EC enteroendocrine cell': 'enteroendocrine cell',
    'ionocyte': 'epithelial cell',
    'central memory CD8-positive, alpha-beta T cell': 'T cell',
    'group 2 innate lymphoid cell': 'innate lymphoid cell',
    'inflammatory cell': 'immune cell',
    'erythroid progenitor cell': 'progenitor cell',
    'T cell': 'T cell',
    'double-positive, alpha-beta thymocyte': 'thymocyte',
    'intestine goblet cell': 'goblet cell',
    'CD8-positive, alpha-beta cytokine-secreting effector T cell': 'T cell',
    'memory T cell': 'T cell',
    'L5 extratelencephalic projecting glutamatergic cortical neuron': 'neuron',
    'vasa recta ascending limb cell': 'kidney cell',
    'type D enteroendocrine cell': 'enteroendocrine cell',
    'pancreatic PP cell': 'endocrine cell',
    'kidney resident macrophage': 'macrophage',
    'epithelial cell of the proximal tubule': 'epithelial cell',
    'luminal cell of prostate epithelium': 'epithelial cell',
    'anterior lens cell': 'lens cell',
    'retina horizontal cell': 'retinal cell',
    'retinal blood vessel endothelial cell': 'endothelial cell',
    'Leydig cell': 'endocrine cell',
    'fibrocyte': 'fibroblast',
    'duodenum glandular cell': 'epithelial cell',
    'vascular-associated smooth muscle cell': 'smooth muscle cell',
    'kidney collecting duct principal cell': 'kidney cell',
    'immature T cell': 'T cell',
    'mesenchymal cell': 'mesenchymal cell',
    'regular atrial cardiac myocyte': 'cardiomyocyte',
    'microfold cell of the epithelium of the small intestine': 'epithelial cell',
    'lung ciliated cell': 'epithelial cell',
    'paneth cell of the epithelium of the small intestine': 'epithelial cell',
    'endothelial cell of the vascular tree': 'endothelial cell',
    'type I enteroendocrine cell': 'enteroendocrine cell',
    'common lymphoid progenitor': 'progenitor cell',
    'leukocyte': 'immune cell',
    'plasmacytoid dendritic cell': 'dendritic cell',
    'B-1b B cell': 'B cell',
    'colon epithelial cell': 'epithelial cell',
    'peripheral blood mononuclear cell': 'immune cell',
    'immature alpha-beta T cell': 'T cell',
    'elicited macrophage': 'macrophage',
    'fenestrated cell': 'endothelial cell',
    'eurydendroid cell': 'neuron',
    'mesenchymal lymphangioblast': 'mesenchymal cell',
    'double-negative T regulatory cell': 'T cell',
    'lung goblet cell': 'goblet cell',
    'club cell': 'epithelial cell',
    'kidney collecting duct intercalated cell': 'kidney cell',
    'hematopoietic precursor cell': 'progenitor cell',
    'stem cell': 'stem cell',
    'mammary gland epithelial cell': 'epithelial cell',
    'L6b glutamatergic cortical neuron': 'neuron',
    'epithelial cell of the esophagus': 'epithelial cell',
    'skeletal muscle satellite stem cell': 'stem cell',
    'cord blood hematopoietic stem cell': 'stem cell',
    'CD16-negative, CD56-bright natural killer cell, human': 'natural killer cell',
    'decidual natural killer cell, human': 'natural killer cell',
    'type I NK T cell': 'T cell',
    'DN1 thymic pro-T cell': 'T cell',
    'B-1 B cell': 'B cell',
    'fallopian tube secretory epithelial cell': 'epithelial cell',
    'extravillous trophoblast': 'trophoblast',
    'enteric smooth muscle cell': 'smooth muscle cell',
    'uterine smooth muscle cell': 'smooth muscle cell',
    'epicardial adipocyte': 'adipocyte',
    'L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex': 'neuron',
    'rod bipolar cell': 'retinal cell',
    'valve cell': 'endothelial cell',
    'kidney interstitial cell': 'interstitial cell',
    'intestinal crypt stem cell of small intestine': 'stem cell',
    'T-helper 1 cell': 'T cell',
    'macrophage dendritic cell progenitor': 'progenitor cell',
    'activated CD8-positive, alpha-beta T cell': 'T cell',
    'melanocyte of skin': 'cell',
    'absorptive cell': 'epithelial cell',
    'subcutaneous fat cell': 'adipocyte',
    'smooth muscle fiber of ileum': 'smooth muscle cell',
    'cardiac muscle myoblast': 'muscle cell',
    'renal principal cell': 'kidney cell',
    'endothelial cell': 'endothelial cell',
    'parietal epithelial cell': 'epithelial cell',
    'kidney loop of Henle cortical thick ascending limb epithelial cell': 'kidney epithelial cell',
    'medium spiny neuron': 'neuron',
    'myeloid leukocyte': 'myeloid cell',
    'primordial germ cell': 'germ cell',
    'tracheobronchial smooth muscle cell': 'smooth muscle cell',
    'capillary endothelial cell': 'endothelial cell',
    'tracheobronchial goblet cell': 'goblet cell',
    'enterocyte of epithelium proper of ileum': 'epithelial cell',
    'large pre-B-II cell': 'B cell',
    'bronchial smooth muscle cell': 'smooth muscle cell',
    'astrocyte': 'glial cell',
    'hematopoietic stem cell': 'stem cell',
    'effector memory CD8-positive, alpha-beta T cell, terminally differentiated': 'T cell',
    'enteroendocrine cell': 'enteroendocrine cell',
    'hematopoietic multipotent progenitor cell': 'progenitor cell',
    'CD8-positive, alpha-beta T cell': 'T cell',
    'Schwann cell': 'neuroglial cell',
    'mononuclear cell': 'immune cell',
    'myeloid dendritic cell': 'dendritic cell',
    'cell of skeletal muscle': 'muscle cell',
    'basal cell of epithelium of trachea': 'epithelial cell',
    'embryonic stem cell': 'stem cell',
    'neoplastic cell': 'tumor cell',
    'megakaryocyte': 'megakaryocyte',
    'epithelial cell of thymus': 'epithelial cell',
    'activated CD8-positive, alpha-beta T cell, human': 'T cell',
    'centroblast': 'B cell',
    'erythrocyte': 'blood cell',
    'memory B cell': 'B cell',
    'gut endothelial cell': 'endothelial cell',
    'neural progenitor cell': 'neural stem cell',
    'IgM plasma cell': 'plasma cell',
    'basal cell of epidermis': 'epithelial cell',
    'colon macrophage': 'macrophage',
    'epithelial cell of lacrimal sac': 'epithelial cell',
    'lung microvascular endothelial cell': 'endothelial cell',
    'bronchus fibroblast of lung': 'fibroblast',
    'podocyte (sensu Diptera)': 'podocyte',
    'amacrine cell': 'neuron',
    'corneal endothelial cell': 'endothelial cell',
    'native cell': 'cell',
    'ciliated cell': 'epithelial cell',
    'DN4 thymocyte': 'thymocyte',
    'liver dendritic cell': 'dendritic cell',
    'effector memory CD8-positive, alpha-beta T cell': 'T cell',
    'neural stem cell': 'stem cell',
    'T follicular helper cell': 'T cell',
    'kidney capillary endothelial cell': 'endothelial cell',
    'plasmacytoid dendritic cell, human': 'dendritic cell',
    'kidney cortex artery cell': 'endothelial cell',
    'brush cell': 'epithelial cell',
    'cytotoxic T cell': 'T cell',
    'primary cultured cell': 'cell',
    'basophil mast progenitor cell': 'progenitor cell',
    'sncg GABAergic cortical interneuron': 'neuron',
    'kidney cell': 'kidney cell',
    'T-helper 2 cell': 'T cell',
    'columnar/cuboidal epithelial cell': 'epithelial cell',
    'early promyelocyte': 'myeloid cell',
    'memory regulatory T cell': 'T cell',
    'glial cell': 'neuroglial cell',
    'sperm': 'germ cell',
    'kidney proximal straight tubule epithelial cell': 'kidney epithelial cell',
    'kidney connecting tubule epithelial cell': 'kidney epithelial cell',
    'CD4-positive, alpha-beta memory T cell': 'T cell',
    'cd4-positive, alpha-beta t cell': 'T cell',
    'stem cell of epidermis': 'stem cell',
    'centrilobular region hepatocyte': 'hepatocyte',
    'transitional stage B cell': 'B cell',
    'GABAergic neuron': 'neuron',
    'vasa recta descending limb cell': 'kidney cell',
    'mature astrocyte': 'glial cell',
    'granulocyte': 'myeloid cell',
    'L2/3-6 intratelencephalic projecting glutamatergic cortical neuron': 'neuron',
    'epithelial cell of large intestine': 'epithelial cell',
    'respiratory basal cell': 'epithelial cell',
    'tracheobronchial serous cell': 'epithelial cell',
    'pancreatic ductal cell': 'epithelial cell',
    'colon goblet cell': 'goblet cell',
    'astrocyte of the cerebellum': 'glial cell',
    'epithelial cell': 'epithelial cell',
    'intestinal crypt stem cell of colon': 'stem cell',
    'goblet cell': 'goblet cell',
    'interstitial cell of Cajal': 'smooth muscle cell',
    'mesothelial fibroblast': 'fibroblast',
    'granulocytopoietic cell': 'myeloid cell',
    'kidney distal convoluted tubule epithelial cell': 'kidney epithelial cell',
    'thyroid follicular cell': 'epithelial cell',
    'midzonal region hepatocyte': 'hepatocyte',
    'CD8-positive, alpha-beta memory T cell, CD45RO-positive': 'T cell',
    'fibroblast of cardiac tissue': 'fibroblast',
    'slow muscle cell': 'muscle cell',
    'vein endothelial cell': 'endothelial cell',
    'immature innate lymphoid cell': 'innate lymphoid cell',
    'lung neuroendocrine cell': 'neuroendocrine cell',
    'corticothalamic-projecting glutamatergic cortical neuron': 'neuron',
    'L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex': 'neuron',
    'professional antigen presenting cell': 'antigen-presenting cell',
    'epithelial cell of sweat gland': 'epithelial cell',
    'conjunctival epithelial cell': 'epithelial cell',
    'type L enteroendocrine cell': 'enteroendocrine cell',
    'macroglial cell': 'glial cell',
    'abnormal cell': 'cell',
    'enterocyte of epithelium proper of large intestine': 'epithelial cell',
    'enteric neuron': 'neuron',
    'IgG plasmablast': 'plasma cell',
    'L4/5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex': 'neuron',
    'adipocyte of epicardial fat of left ventricle': 'adipocyte',
    'glomerular capillary endothelial cell': 'endothelial cell',
    'bladder urothelial cell': 'epithelial cell',
    'medullary thymic epithelial cell': 'epithelial cell',
    'non-pigmented ciliary epithelial cell': 'epithelial cell',
    'CD16-positive, CD56-dim natural killer cell, human': 'natural killer cell',
    'pyramidal neuron': 'neuron',
    'corneal epithelial cell': 'epithelial cell',
    'small intestine goblet cell': 'goblet cell',
    'ventricular cardiac muscle cell': 'muscle cell',
    'neutrophil progenitor cell': 'progenitor cell',
    'forebrain radial glial cell': 'glial cell',
    'lens epithelial cell': 'epithelial cell',
    'epithelial cell of exocrine pancreas': 'epithelial cell',
    'hypendymal cell': 'ependymal cell',
    'Hofbauer cell': 'macrophage',
    'cortical interneuron': 'neuron',
    'proerythroblast': 'progenitor cell',
    'fibroblast': 'fibroblast',
    'pigmented epithelial cell': 'epithelial cell',
    'cholangiocyte': 'epithelial cell',
    'ciliated columnar cell of tracheobronchial tree': 'epithelial cell',
    'cerebral cortex endothelial cell': 'endothelial cell',
    'ileal goblet cell': 'goblet cell',
    'naive thymus-derived CD8-positive, alpha-beta T cell': 'T cell',
    'urethra urothelial cell': 'epithelial cell',
    'myeloid cell': 'myeloid cell',
    'brush cell of epithelium proper of large intestine': 'epithelial cell',
    'Langerhans cell': 'dendritic cell',
    'endocardial cell': 'endothelial cell',
    'papillary tips cell': 'cell',
    'CD14-positive, CD16-positive monocyte': 'monocyte',
    'thymocyte': 'thymocyte',
    'type N enteroendocrine cell': 'enteroendocrine cell',
    'enucleate erythrocyte': 'blood cell',
    'skeletal muscle fiber': 'muscle cell',
    'ON-bipolar cell': 'retinal cell',
    'ciliary muscle cell': 'muscle cell',
    'glandular epithelial cell': 'epithelial cell',
    'epithelial cell of stratum germinativum of esophagus': 'epithelial cell',
    'CD1c-positive myeloid dendritic cell': 'dendritic cell',
    'intermediate monocyte': 'monocyte',
    'foveolar cell of stomach': 'epithelial cell',
    'vascular leptomeningeal cell': 'endothelial cell',
    'lymphocyte': 'immune cell',
    'central nervous system macrophage': 'macrophage',
    'immature neutrophil': 'neutrophil',
    'kidney proximal convoluted tubule epithelial cell': 'kidney epithelial cell',
    'renal interstitial pericyte': 'connective tissue cell',
    'mature conventional dendritic cell': 'dendritic cell',
    'endothelial cell of sinusoid': 'endothelial cell',
    'IgA plasmablast': 'plasma cell',
    'bone marrow cell': 'cell',
    'central memory CD4-positive, alpha-beta T cell': 'T cell',
    'vip GABAergic cortical interneuron': 'neuron',
    'alveolar type 2 fibroblast cell': 'fibroblast',
    'radial glial cell': 'glial cell',
    'keratocyte': 'cell',
    'hepatic stellate cell': 'cell',
    'reticular cell': 'cell',
    'neuron associated cell': 'neuron',
    'pericyte': 'connective tissue cell',
    'inhibitory motor neuron': 'neuron',
    'germ cell': 'cell',
    'progenitor cell of endocrine pancreas': 'progenitor cell',
    'class switched memory B cell': 'B cell',
    'early pro-B cell': 'B cell',
    'endothelial cell of hepatic sinusoid': 'endothelial cell',
    'mucosal invariant T cell': 'T cell',
    'migratory enteric neural crest cell': 'neural crest cell',
    'mesothelial cell of pleura': 'mesothelial cell',
    'renal alpha-intercalated cell': 'kidney cell',
    'mesothelial cell of epicardium': 'mesothelial cell',
    'transit amplifying cell of colon': 'colon cell',
    'neuroendocrine cell': 'neuroendocrine cell',
    'tissue-resident macrophage': 'macrophage',
    'kidney cortex tubule cell': 'kidney cell',
    'bronchial goblet cell': 'goblet cell',
    'granulosa cell': 'cell',
    'lung macrophage': 'macrophage',
    'smooth muscle cell of trachea': 'smooth muscle cell',
    'endothelial cell of periportal hepatic sinusoid': 'endothelial cell',
    'pulmonary artery endothelial cell': 'endothelial cell',
    'late pro-B cell': 'B cell',
    'oocyte': 'germ cell',
    'fraction A pre-pro B cell': 'B cell',
    'bladder cell': 'cell',
    'mature gamma-delta T cell': 'T cell',
    'sst GABAergic cortical interneuron': 'neuron',
    'basal cell of prostate epithelium': 'epithelial cell',
    'enucleated reticulocyte': 'blood cell',
    'epidermal Langerhans cell': 'dendritic cell',
    'small pre-B-II cell': 'B cell',
    'basophil': 'cell',
    'muscle precursor cell': 'muscle cell',
    'gamma-delta T cell': 'T cell',
    'intestinal crypt stem cell': 'stem cell',
    'sst chodl GABAergic cortical interneuron': 'neuron',
    'macula densa epithelial cell': 'epithelial cell',
    'intestinal crypt stem cell of large intestine': 'stem cell',
    'myeloid dendritic cell, human': 'dendritic cell',
    'monocyte': 'monocyte',
    'pancreatic acinar cell': 'epithelial cell',
    'endothelial cell of coronary artery': 'endothelial cell',
    'eukaryotic cell': 'cell',
    'NKp44-negative group 3 innate lymphoid cell, human': 'innate lymphoid cell',
    'urothelial cell': 'epithelial cell',
    'interneuron': 'neuron',
    'duct epithelial cell': 'epithelial cell',
    'keratinocyte stem cell': 'stem cell',
    'adventitial cell': 'cell',
    'multi-ciliated epithelial cell': 'epithelial cell',
    'Sertoli cell': 'cell',
    'secondary lens fiber': 'cell',
    'pancreatic A cell': 'epithelial cell',
    'naive regulatory T cell': 'T cell',
    'ciliated epithelial cell': 'epithelial cell',
    'cerebellar granule cell': 'neuron',
    'epithelial cell of small intestine': 'epithelial cell',
    'mesothelial cell': 'mesothelial cell',
    'mural cell': 'cell',
    'epithelial cell of prostate': 'epithelial cell',
    'tonsil germinal center B cell': 'B cell',
    'lung secretory cell': 'epithelial cell',
    'granular cell of epidermis': 'epithelial cell',
    'myofibroblast cell': 'myofibroblast',
    'keratinocyte': 'epithelial cell',
    'smooth muscle cell': 'smooth muscle cell',
    'enterocyte': 'epithelial cell',
    'PP cell': 'cell',
    'pancreatic epsilon cell': 'epithelial cell',
    'naive T cell': 'T cell',
    'pro-B cell': 'B cell',
    'b cell': 'B cell',
    'basal epithelial cell of tracheobronchial tree': 'epithelial cell',
    'epithelial cell of nephron': 'epithelial cell',
    'epithelial cell of urethra': 'epithelial cell',
    'effector CD4-positive, alpha-beta T cell': 'T cell',
    'mesodermal cell': 'cell',
    'pulmonary interstitial fibroblast': 'fibroblast',
    'pancreatic stellate cell': 'cell',
    'intestinal enteroendocrine cell': 'enteroendocrine cell',
    'skeletal muscle satellite cell': 'stem cell',
    'lung pericyte': 'connective tissue cell',
    'CD8-positive, alpha-beta memory T cell': 'T cell',
    'cd8-positive, alpha-beta t cell': 'T cell',
    'common dendritic progenitor': 'progenitor cell',
    'prostate stromal cell': 'cell',
    'double negative thymocyte': 'thymocyte',
    'peptic cell': 'cell',
    'chondrocyte': 'connective tissue cell',
    'acinar cell of salivary gland': 'epithelial cell',
    'P/D1 enteroendocrine cell': 'enteroendocrine cell',
    'neutrophil': 'neutrophil',
    'germinal center B cell': 'B cell',
    'cerebral cortex GABAergic interneuron': 'neuron',
    'mucus secreting cell': 'epithelial cell',
    'intestinal tuft cell': 'epithelial cell',
    'ovarian surface epithelial cell': 'epithelial cell',
    'ciliated cell of the bronchus': 'epithelial cell',
    'nasal mucosa goblet cell': 'goblet cell',
    'common myeloid progenitor': 'progenitor cell',
    'glomerular endothelial cell': 'endothelial cell',
    'mast cell': 'mast cell',
    'blood cell': 'blood cell',
    'regulatory T cell': 'T cell',
    'retinal rod cell': 'retinal cell',
    'naive thymus-derived CD4-positive, alpha-beta T cell': 'T cell',
    'primary sensory neuron': 'neuron',
    'respiratory hillock cell': 'epithelial cell',
    'CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell': 'T cell',
    'eosinophil': 'eosinophil',
    'erythroblast': 'progenitor cell',
    'neuroblast (sensu Vertebrata)': 'neuron',
    'mononuclear phagocyte': 'macrophage',
    'effector CD8-positive, alpha-beta T cell': 'T cell',
    'naive B cell': 'B cell',
    'glandular cell of esophagus': 'epithelial cell',
    'innate lymphoid cell': 'innate lymphoid cell',
    'tuft cell of colon': 'epithelial cell',
    'B-2 B cell': 'B cell',
    'brush cell of trachea': 'epithelial cell',
    'secretory cell': 'cell',
    'fibroblast of connective tissue of glandular part of prostate': 'fibroblast',
    'prickle cell': 'cell',
    'megakaryocyte-erythroid progenitor cell': 'progenitor cell',
    'alternatively activated macrophage': 'macrophage',
    'pvalb GABAergic cortical interneuron': 'neuron',
    'cell': 'cell',
    'connective tissue cell': 'connective tissue cell',
    'vascular leptomeningeal cell (Mmus)': 'endothelial cell',
    'kidney efferent arteriole endothelial cell': 'endothelial cell',
    'brain pericyte': 'connective tissue cell',
    'luminal epithelial cell of mammary gland': 'epithelial cell',
    'melanocyte': 'cell',
    'late promyelocyte': 'progenitor cell',
    'mature B cell': 'B cell',
    'smooth muscle cell of the pulmonary artery': 'smooth muscle cell',
    'sebaceous gland cell': 'epithelial cell',
    'kidney loop of Henle epithelial cell': 'epithelial cell',
    'lens fiber cell': 'epithelial cell',
    'immature Schwann cell': 'glial cell',
    'female germ cell': 'germ cell',
    'erythroid progenitor cell, mammalian': 'progenitor cell',
    'CD14-low, CD16-positive monocyte': 'monocyte',
    'erythroid lineage cell': 'blood cell',
    'promonocyte': 'monocyte',
    'CD4-positive, alpha-beta cytotoxic T cell': 'T cell',
    'interstitial cell of ovary': 'cell',
    'endothelial cell of uterus': 'endothelial cell',
    'granulocyte monocyte progenitor cell': 'progenitor cell',
    'neural cell': 'neuron',
    'cardiac endothelial cell': 'endothelial cell',
    'mesothelial cell of visceral pleura': 'mesothelial cell',
    'conventional dendritic cell': 'dendritic cell',
    'ependymal cell': 'cell',
    'epithelial cell of alveolus of lung': 'epithelial cell',
    'aortic endothelial cell': 'endothelial cell',
    'tanycyte': 'cell',
    'platelet': 'blood cell',
    'fast muscle cell': 'muscle cell',
    'non-classical monocyte': 'monocyte',
    'osteoclast': 'cell',
    'kidney epithelial cell': 'epithelial cell',
    'myoepithelial cell': 'cell',
    'squamous epithelial cell': 'epithelial cell',
    'immature NK T cell': 'T cell',
    'mature nk t cell': 'T cell',
    'skeletal muscle fibroblast': 'fibroblast',
    'peripheral nervous system neuron': 'neuron',
    'fat cell': 'cell',
    'neural crest cell': 'neural crest cell',
    'immature B cell': 'B cell',
    'L5/6 near-projecting glutamatergic neuron of the primary motor cortex': 'neuron',
    'plasma cell': 'plasma cell',
    'mature microglial cell': 'microglial cell',
    'CD4-positive, alpha-beta memory T cell, CD45RO-positive': 'T cell',
    'gut absorptive cell': 'epithelial cell',
    'GIP cell': 'cell',
    'male germ cell': 'germ cell',
    'Kupffer cell': 'macrophage',
    'hepatocyte': 'cell',
    'syncytiotrophoblast cell': 'trophoblast',
    'mucous neck cell': 'epithelial cell',
    'near-projecting glutamatergic cortical neuron': 'neuron',
    'OFF-bipolar cell': 'retinal cell',
    'endothelial cell of artery': 'endothelial cell',
    'adipocyte of breast': 'adipocyte',
    'meis2 expressing cortical GABAergic cell': 'neuron',
    'skin fibroblast': 'fibroblast',
    'transit amplifying cell': 'cell',
    'type B pancreatic cell': 'epithelial cell',
    'endocrine cell': 'endocrine cell',
    'respiratory epithelial cell': 'epithelial cell',
    'inhibitory interneuron': 'neuron',
    'alveolar type 1 fibroblast cell': 'fibroblast',
    'unswitched memory B cell': 'B cell',
    'CD4-positive, CD25-positive, alpha-beta regulatory T cell': 'T cell',
    'lamp5 GABAergic cortical interneuron': 'neuron',
    'classical monocyte': 'monocyte',
    'Cajal-Retzius cell': 'neuron',
    'endothelial tip cell': 'endothelial cell',
    'salivary gland cell': 'epithelial cell',
    'muscle cell': 'muscle cell',
    'effector memory CD4-positive, alpha-beta T cell': 'T cell',
    'B-1a B cell': 'B cell',
    'CD4-positive, alpha-beta thymocyte': 'thymocyte',
    'type G enteroendocrine cell': 'enteroendocrine cell',
    'intraepithelial lymphocyte': 'lymphocyte',
    'neuronal receptor cell': 'neuron',
    'epithelial cell of uterus': 'epithelial cell',
    'alveolar macrophage': 'macrophage',
    'endosteal cell': 'cell',
    'glioblast': 'cell',
    'motor neuron': 'neuron',
    'oogonial cell': 'germ cell',
    'hippocampal neuron': 'neuron',
    'intrahepatic cholangiocyte': 'epithelial cell',
    'hair follicular keratinocyte': 'epithelial cell',
    'somatic cell': 'cell',
    'vascular lymphangioblast': 'endothelial cell',
    'neuron': 'neuron',
    'CD141-positive myeloid dendritic cell': 'dendritic cell',
    'animal cell': 'cell',
    'T follicular regulatory cell': 'T cell',
    'mature alpha-beta T cell': 'T cell',
    'myeloid lineage restricted progenitor cell': 'progenitor cell',
    'myoepithelial cell of mammary gland': 'cell',
    'follicular B cell': 'B cell',
    'exhausted T cell': 'T cell',
    'neuroepithelial stem cell': 'stem cell',
    'mesangial cell': 'cell',
    'fibroblast of connective tissue of prostate': 'fibroblast',
    'endothelial stalk cell': 'endothelial cell',
    'kidney afferent arteriole endothelial cell': 'endothelial cell',
    'tongue muscle cell': 'muscle cell',
    'centrocyte': 'B cell',
    'lymphoid lineage restricted progenitor cell': 'progenitor cell',
    'T-helper 22 cell': 'T cell',
    'surface ectodermal cell': 'epithelial cell',
    'transit amplifying cell of small intestine': 'cell',
    'Bergmann glial cell': 'glial cell',
    'brush cell of trachebronchial tree': 'epithelial cell',
    'Merkel cell': 'epithelial cell',
    'malignant cell': 'cell',
    'None': 'cell',
    'mature NK T cell': 'T cell',
    'CD34-positive, CD38-negative hematopoietic stem cell': 'stem cell',
    'hematopoietic cell': 'hematopoietic cell',
    'enterocyte of epithelium of small intestine': 'epithelial cell',
    'precursor cell': 'cell',
    'fibroblast of lung': 'fibroblast',
    'reticulocyte': 'blood cell',
    'Purkinje cell': 'neuron',
    'astrocyte of the cerebral cortex': 'glial cell',
    'enteroendocrine cell of small intestine': 'enteroendocrine cell',
    'kidney loop of Henle thick ascending limb epithelial cell': 'epithelial cell',
    'inflammatory macrophage': 'macrophage',
    'serous secreting cell': 'cell',
    'CD8-alpha alpha positive, gamma-delta intraepithelial T cell': 'T cell',
    'primitive red blood cell': 'blood cell',
    'macrophage': 'macrophage',
    'periportal region hepatocyte': 'hepatocyte',
    'respiratory goblet cell': 'epithelial cell',
    'pneumocyte': 'epithelial cell',
    'early T lineage precursor': 'T cell',
    'phagocyte': 'cell',
    'bronchial epithelial cell': 'epithelial cell',
    'theca cell': 'cell',
    'prostate gland microvascular endothelial cell': 'endothelial cell',
    'DN3 thymocyte': 'thymocyte',
    'fibroblast of breast': 'fibroblast',
    'kidney collecting duct epithelial cell': 'epithelial cell',
    'smooth muscle cell of sphincter of pupil': 'smooth muscle cell',
    'group 3 innate lymphoid cell': 'innate lymphoid cell',
    'CD14-positive monocyte': 'monocyte',
    'type I pneumocyte': 'epithelial cell',
    'type i pneumocyte': 'epithelial cell',
    'epithelial cell of lower respiratory tract': 'epithelial cell',
    'type II pneumocyte': 'epithelial cell',
    'type ii pneumocyte': 'epithelial cell',
    'CD4-positive, alpha-beta T cell': 'T cell',
    'kidney collecting duct cell': 'epithelial cell',
    'myometrial cell': 'cell',
    'kidney interstitial fibroblast': 'fibroblast',
    'supporting cell': 'cell',
    'placental villous trophoblast': 'trophoblast',
    'aortic smooth muscle cell': 'smooth muscle cell',
    'retinal ganglion cell': 'neuron',
    'fibroblast of mammary gland': 'fibroblast',
    'CD8-positive, alpha-beta cytokine secreting effector T cell': 'T cell',
'epithelial cell of proximal tubule': 'epithelial cell',
'vascular associated smooth muscle cell': 'smooth muscle cell',
'microfold cell of epithelium of small intestine': 'epithelial cell',
'paneth cell of epithelium of small intestine': 'epithelial cell',
'endothelial cell of vascular tree': 'endothelial cell',
'double negative T regulatory cell': 'T cell',
'epithelial cell of esophagus': 'epithelial cell',
'enterocyte of epithelium of large intestine': 'epithelial cell',
'mature T cell': 'T cell',
'oligodendrocyte': 'glial cell',
'cardiac mesenchymal cell': 'cell',
'fetal cardiomyocyte': 'cardiomyocyte',
'CD14-positive, CD16-negative classical monocyte': 'monocyte',
'natural T-regulatory cell': 'T cell',
'mesenchymal stem cell of adipose tissue': 'stem cell',
'immature natural killer cell': 'natural killer cell',
'acinar cell': 'cell',
'pancreatic D cell': 'endocrine cell',
'stromal cell of ovary': 'cell',
'group 2 innate lymphoid cell, human': 'innate lymphoid cell',
'pituitary gland cell': 'cell',
'IgG-negative class switched memory B cell': 'B cell',
'podocyte': 'epithelial cell',
'stratified epithelial cell': 'epithelial cell',
'intestinal epithelial cell': 'epithelial cell',
'dendritic cell': 'dendritic cell',
'plasmablast': 'B cell',
'preosteoblast': 'cell',
'fibroblast of connective tissue of nonglandular part of prostate': 'fibroblast',
'L6 corticothalamic-projecting glutamatergic cortical neuron': 'neuron',
'microglial cell': 'microglial cell',
'decidual cell': 'cell',
'alpha-beta T cell': 'T cell',
'fibro/adipogenic progenitor cell': 'progenitor cell',
'eye photoreceptor cell': 'photoreceptor cell',
'kidney loop of Henle ascending limb epithelial cell': 'epithelial cell',
'renal beta-intercalated cell': 'epithelial cell',
'pre-conventional dendritic cell': 'dendritic cell',
'ILC1, human': 'innate lymphoid cell',
'precursor B cell': 'B cell',
'IgA plasma cell': 'plasma cell',
'Mueller cell': 'glial cell',
'choroid plexus epithelial cell': 'epithelial cell',
'pulmonary ionocyte': 'cell',
'enterocyte of colon': 'epithelial cell',
'tendon cell': 'cell',
'contractile cell': 'cell',
'paneth cell': 'epithelial cell',
'serous cell of epithelium of trachea': 'epithelial cell',
'glycinergic neuron': 'neuron',
'regular ventricular cardiac myocyte': 'cardiomyocyte',
'kidney loop of Henle medullary thick ascending limb epithelial cell': 'epithelial cell',
'retinal cone cell': 'photoreceptor cell',
'oligodendrocyte precursor cell': 'glial cell',
'CD8-positive, alpha-beta cytotoxic T cell': 'T cell',
'basal cell': 'epithelial cell',
'megakaryocyte progenitor cell': 'progenitor cell',
'enteroendocrine cell of colon': 'enteroendocrine cell',
'activated CD4-positive, alpha-beta T cell, human': 'T cell',
'promyelocyte': 'progenitor cell',
'pro-T cell': 'T cell',
'myelocyte': 'progenitor cell',
'cardiac muscle cell': 'cardiomyocyte',
'pancreatic endocrine cell': 'endocrine cell',
'basal epithelial cell of prostatic duct': 'epithelial cell',
'early lymphoid progenitor': 'progenitor cell',
'tracheal goblet cell': 'epithelial cell',
'pre-B-I cell': 'B cell',
'endothelial cell of pericentral hepatic sinusoid': 'endothelial cell',
'osteoblast': 'cell',
'NKp44-positive group 3 innate lymphoid cell, human': 'innate lymphoid cell',
'pigmented ciliary epithelial cell': 'epithelial cell',
'IgG memory B cell': 'B cell',
'epidermal cell': 'epithelial cell',
'serous cell of epithelium of bronchus': 'epithelial cell',
'stromal cell': 'cell',
'IgG plasma cell': 'plasma cell',
'chandelier pvalb GABAergic cortical interneuron': 'neuron',
'large intestine goblet cell': 'epithelial cell',
'dendritic cell, human': 'dendritic cell',
'CD8-positive, alpha-beta thymocyte': 'thymocyte',
'leptomeningeal cell': 'cell',
'pre-natural killer cell': 'natural killer cell',
'activated CD4-positive, alpha-beta T cell': 'T cell',
'cerebellar Golgi cell': 'neuron',
'seminal vesicle glandular cell': 'epithelial cell',
'follicular dendritic cell': 'dendritic cell',
'kidney glomerular epithelial cell': 'epithelial cell',
'smooth muscle cell of prostate': 'smooth muscle cell',
'parietal cell': 'epithelial cell',
'retinal pigment epithelial cell': 'epithelial cell',
'glutamatergic neuron': 'neuron',
'M cell of gut': 'epithelial cell',
'endothelial cell of lymphatic vessel': 'endothelial cell',
'cardiac neuron': 'neuron',
'T-helper 17 cell': 'T cell',
'blood vessel endothelial cell': 'endothelial cell',
'natural killer cell': 'natural killer cell',
'Schwann cell precursor': 'glial cell',
'retinal bipolar neuron': 'neuron',
'caudal ganglionic eminence derived GABAergic cortical interneuron': 'neuron',
'progenitor cell': 'progenitor cell',
'renal intercalated cell': 'epithelial cell',
   'pancreatic endocrine cell': 'endocrine cell',
    'pancreatic PP cell': 'endocrine cell',
    'pancreatic D cell': 'endocrine cell',
    'CM': 'cell',
    'Blastula': 'cell',
    'Involuting marginal zone': 'cell',
    'Epidermal progenitor': 'progenitor cell',
    'Non-neural ectoderm': 'cell',
    'Neuroectoderm': 'neuron',
    'Endoderm': 'cell',
    'Spemann organizer': 'cell',
    'Ionocyte': 'cell',
    'Germline': 'germ cell',
    'Goblet cell': 'goblet cell',
    '1_Corneal epithelium': 'epithelial cell',
    '3_Macrophage': 'macrophage',
    '2_BeamA': 'cell',
    '16_Pericyte': 'connective tissue cell',
    '13_Pericyte': 'connective tissue cell',
    '14_Collector channel': 'cell',
    '4_Ciliary muscle': 'muscle cell',
    '6_JCT': 'cell',
    '12_Melanocyte': 'cell',
    '9_Corneal epithelium': 'epithelial cell',
    '7_Fibroblast': 'fibroblast',
    '8_Melanocyte': 'cell',
    '5_Schwann cell': 'glial cell',
    '15_Beam X': 'cell',
    '20_B cell': 'B cell',
    '17_Corneal epithelium': 'epithelial cell',
    '18_Corneal epithelium': 'epithelial cell',
    '11_Vascular': 'endothelial cell',
    '10_NK/T cell': 'T cell',
    "19_SChlemm's Canal": 'cell',
    'Leydig cell': 'endocrine cell',
    'missing': 'cell',
    '2_Ciliary muscle': 'muscle cell',
    '1_Beam X': 'cell',
    "7_SChlemm's Canal": 'cell',
    '5_Nonmyelinating schwann cell': 'glial cell',
    '8_Endothelium': 'endothelial cell',
    '14_Myelinating schwann cell': 'glial cell',
    '11_Pericyte': 'connective tissue cell',
    '6_NK/T': 'T cell',
    '4_Beam A': 'cell',
    '9_Melanocyte': 'cell',
    '10_JCT': 'cell',
    '13_NK/T cell': 'T cell',
    '15_Macrophage': 'macrophage',
    '12_Pericyte': 'connective tissue cell',
    'nan': 'cell',
    'lung endothelial cell': 'endothelial cell',
    'Fraction A pre-pro B cell': 'B cell',
    'cardiomyocyte': 'cardiomyocyte',
    'CD8+ T cell': 'T cell',
    'vascular endothelial': 'endothelial cell',
    'nkt': 'natural killer cell',
    'smc': 'smooth muscle cell',
    'nk': 'natural killer cell',
    'adipocyte': 'adipocyte',
    'b': 'B cell',
    'T reg': 'T cell',
    'plasma': 'plasma cell',
    'lymphatic endothelial': 'endothelial cell',
    'Pluripotent': 'stem cell',
    'Dorsal organizer': 'cell',
    'Apoptotic-like': 'cell',
    'Notochord': 'cell',
    'Presomitic mesoderm': 'mesenchymal cell',
    'Tailbud': 'cell',
    'Intermediate mesoderm': 'mesenchymal cell',
    'Epithelial': 'epithelial cell',
    'Fibroblast': 'fibroblast',
    'Endothelial': 'endothelial cell',
    'Immune': 'immune cell',
    'Schwann': 'glial cell',
    'Endocrine': 'endocrine cell',
    'B+Plasma': 'B cell',
    'T+NK': 'T cell',
    'Endo.+Macro.': 'macrophage',
    'Epi': 'epithelial cell',
    'TNKILC': 'innate lymphoid cell',
    'B': 'B cell',
    'Mast': 'mast cell',
    'Plasma': 'plasma cell',
    'Myeloid': 'myeloid cell',
    'Strom': 'cell',
    'endocrine cell': 'endocrine cell',
    'Cones': 'retinal cell',
    'Horizontal': 'neuron',
    'Rods': 'retinal cell',
    'Goblet 2': 'goblet cell',
    'Tuft-like': 'cell',
    'Progenitor-like 2': 'progenitor cell',
    'EC3': 'endothelial cell',
    'Hepatocytes 1': 'hepatocyte',
    'LRE 1': 'cell',
    'EC4': 'endothelial cell',
    'Goblet-like': 'goblet cell',
    'Epidermis 2': 'epithelial cell',
    'Mesenchymal 2': 'mesenchymal cell',
    'Epidermis 3': 'epithelial cell',
    'Hepatocytes 2': 'hepatocyte',
    'Progenitor-like 1': 'progenitor cell',
    'Goblet 1': 'goblet cell',
    'Endocrine 2': 'endocrine cell',
    'Mesenchymal 1': 'mesenchymal cell',
    'Acinar 3': 'cell',
    'Vascular Smooth Muscle': 'smooth muscle cell',
    'Neuronal': 'neuron',
    'Best4/Otop2': 'cell',
    'Mesenchymal 3': 'mesenchymal cell',
    'EC5': 'endothelial cell',
    'Endocrine 1': 'endocrine cell',
    'Vascular Endothelial': 'endothelial cell',
    'Hepatocytes 3': 'hepatocyte',
    'EC2': 'endothelial cell',
    'Leukocytes 2': 'blood cell',
    'Mesenchymal 4': 'mesenchymal cell',
    'EC1': 'endothelial cell',
    'Epidermis 1': 'epithelial cell',
    'Leukocytes 1': 'blood cell',
    'Muscle': 'muscle cell',
    'Acinar 2': 'cell',
    'LRE 2': 'cell',
    'Acinar 1': 'cell',
    'Endocrine 3': 'endocrine cell',
    'EC6': 'endothelial cell',
    'Mesenchymal 5': 'mesenchymal cell',
    'Neuron': 'neuron',
    'paraxial_mesoderm': 'mesenchymal cell',
    'central_nervous_system': 'neuron',
    'endoderm': 'endothelial cell',
    'mesenchyme': 'mesenchymal cell',
    'periderm': 'epithelial cell',
    'lateral_mesoderm': 'mesenchymal cell',
    'intermediate_mesoderm': 'mesenchymal cell',
    'hematopoietic_system': 'hematopoietic cell',
    'notochord': 'cell',
    'neural_crest': 'neural crest cell',
    'LSEC-Z23': 'endothelial cell',
    'CD163+Macrophage': 'macrophage',
    'Kuppfer cells': 'macrophage',
    'NK': 'natural killer cell',
    'Plasma cells': 'plasma cell',
    'Myocyte': 'muscle cell',
    'Erythroid cells': 'blood cell',
    'T/NKT': 'T cell',
    'MAIT': 'T cell',
    'Fibroblast (EC)': 'fibroblast',
    'spermatocyte': 'germ cell',
    'spermatid': 'germ cell',
    'pericyte cell': 'connective tissue cell',
    'spermatogonium': 'germ cell',
    'pancreatic B cell': 'endocrine cell',
    'Purkinje myocyte': 'muscle cell',
    'non-myelinating Schwann cell': 'glial cell',
    'nodal myocyte': 'muscle cell',
    'brush cell of bronchus': 'epithelial cell',
    'DCT': 'kidney cell',
    'PEC': 'endothelial cell',
    'Podocyte': 'kidney cell',
    'vSMC/Pericyte': 'smooth muscle cell',
    'Proliferating T cell': 'T cell',
    'pancreatic endocrine cell': 'endocrine cell',
    'pancreatic PP cell': 'endocrine cell',
    'pancreatic D cell': 'endocrine cell',
    '5_Schwann cell': 'glial cell',
    'Leydig cell': 'endocrine cell',
    '5_Nonmyelinating schwann cell': 'glial cell',
    '14_Myelinating schwann cell': 'glial cell',
    'Melanocyte': 'cell',
    'VascularEndo': 'endothelial cell',
    'BCell': 'B cell',
    'Macrophage': 'macrophage',
    'CribiformJCT': 'cell', # Not sure about the specifics of this one
    'Pericyte': 'connective tissue cell',
    'NKT': 'T cell',
    'MastCell': 'mast cell',
    'ScEndo': 'endothelial cell',
    '1_Uveal': 'cell', # Need more context
    '2_Melanocyte': 'cell',
    '4_Macrophage': 'cell',
    '5_Corneal epithelium': 'epithelial cell',
    '7_Nonpigmented ciliary epithelium': 'epithelial cell',
    '9_Beam Y': 'cell', # Need more context
    '3_Pigmented ciliary epithelium': 'epithelial cell',
    '11_Pigmented epithelium': 'epithelial cell',
    '8_Pericyte': 'connective tissue cell',
    '16_NK/T cell': 'T cell',
    '17_Ciliary muscle': 'muscle cell',
    '10_Vascular Endothelium': 'endothelial cell',
    '13_Corneal': 'epithelial cell',
    '14_Beam A': 'cell', # Need more context
    '12_Corneal endothelium': 'epithelial cell',
    '15_Myoepithelium': 'muscle cell',
    '18_Schwann cell': 'glial cell',
    '13_Nonmyelinating schwann cell': 'glial cell',
    '2_Corneal epithelium': 'epithelial cell',
    '6_Fibroblast': 'fibroblast',
    '3_JCT': 'cell', # Need more context
    '1_Beam A': 'cell', # Need more context
    '8_Corneal epithelium': 'epithelial cell',
    '16_Ciliary muscle': 'muscle cell',
    "14_SChlemm's Canal": 'cell', # Need more context
    '12_Collector channel': 'cell', # Need more context
    '17_Corneal endothelium': 'epithelial cell',
    '7_Corneal epithelium': 'epithelial cell',
    '15_Melanocyte': 'cell',
    '18_Myelinating schwann cell': 'glial cell',
    'C6+ACMSD+Hepatocyte-2': 'hepatocyte',
    'APOA1+APOA2+TTR+Hepatocyte-1': 'hepatocyte',
    'CP+Periportal hepatocytes': 'hepatocyte',
    'LSEC-Z1': 'endothelial cell',
    'Technial/Muscle (Imm)': 'muscle cell', # Technical/muscle cells might be artifacts or technical noise.
    'BANK1+Bcells (Hep)': 'B cell',
    'Macrophage-2': 'macrophage',
    'VWF+ANO2+SPARCL1+': 'cell', # Need more context
    'Cholangiocytes': 'epithelial cell',
    'RSPO3+ fibro': 'fibroblast',
    'Technial/Muscle (Mes)': 'muscle cell',
    'Technial/Muscle (Hep)': 'muscle cell',
    'Mito-rich (Mes)': 'cell', # Need more context, possibly referring to mitochondrial-rich cells
    'LSEC/Hepatocyte Doublet (immune)': 'hepatocyte', # Doublets often refer to two cells captured together during sequencing
    'Doublet Hepatocyte': 'hepatocyte',
    'Periportal hepatocytes (EC)': 'hepatocyte',
    'Plasma (Hep)': 'plasma cell',
    'Stellate cells-1': 'cell',
    'CP+Periportal hepatocytes (Imm)': 'hepatocyte',
    'SPP1+Macrophage': 'macrophage',
    'Monocyte': 'monocyte',
    'T-cell/Doublet (Mes)': 'T cell',
    'Mito-rich hepatocyte': 'hepatocyte',
    'Lymphatic EC': 'endothelial cell',
    'Mito-rich EC': 'endothelial cell',
    'Technial/Muscle (EC)': 'muscle cell',
    'Cycling': 'cell', # Refers to actively dividing cells, but need more context
    'Stellate cells-2': 'cell',
    'Mito-rich doublet (Myeloid)': 'myeloid cell', # Might refer to mitochondrial-rich myeloid cells
    'CP+Periportal hepatocytes (Mes)': 'hepatocyte',
    'Macrophage-1': 'macrophage',
    'Tcells (EC)': 'T cell',
    'Kuppfer (EC)': 'macrophage', # Kupffer cells are liver-specific macrophages
    'SAA1+Hepatocyte (Mes)': 'hepatocyte',
    'EC (Mes)': 'endothelial cell',
    'pancreatic B cell': 'endocrine cell',
    'non-myelinating Schwann cell': 'glial cell',
    'Mito-rich Distal': 'cell', # Need more context
    'TAL': 'cell', # Need more context, possibly related to kidney cells
    'Technical/muscle (Mes)': 'muscle cell',
    'FLT1+PLVAP+EC': 'endothelial cell',
    'CD-PC': 'cell', # Need more context
    'CD-IC-A': 'cell', # Need more context
    'Fibroblast-2': 'fibroblast',
    'PLVAP+EC': 'endothelial cell',
    'VWF+PLVAP+VCAM1+EC': 'endothelial cell',
    'Mito-rich PCT': 'kidney cell', # Need more context, possibly referring to proximal convoluted tubule cells with high mitochondria
    'PCT-S1/S2': 'kidney cell', # Possibly referring to segments of proximal convoluted tubule
    'Stressed_PCT': 'cell',
    'BeamCella': 'cell',  # Context required for a detailed classification
    'BeamCellb': 'cell',  # Context required for a detailed classification
    'CiliaryMuscle': 'muscle cell',
    'SchwannCell-nmy': 'glial cell',
    'SchwannCell-my': 'glial cell',
    'Technical/muscle (EC)': 'muscle cell',  # Technical/muscle cells might be artifacts or technical noise.
    'AQP1+SLC14A1+EC': 'endothelial cell',  # EC generally refers to endothelial cells
    'PCT-S2': 'kidney cell',  # PCT generally refers to the proximal convoluted tubule in the kidney
    'tDL': 'cell',  # Context required for a detailed classification
    'VWF+PLVAP+EC': 'endothelial cell',  
    'Epithelial Doublet': 'epithelial cell',
    'Technical/muscle': 'muscle cell', 
    'REN+Pericyte': 'connective tissue cell',
    'CNT': 'cell',  # Possibly refers to cells in the connecting tubule of the kidney
    'T-cells-1': 'T cell',
    'Glomerular EC': 'endothelial cell',
    'Stressed EC': 'endothelial cell',
    'Fibroblast-1': 'fibroblast',
    'AQP1+PLVAP+EC': 'endothelial cell',
    'PCT-S1': 'kidney cell',
    'T-cells-2': 'T cell',
    'Distal Epi Doublet (PCT)': 'epithelial cell',  # Possibly refers to a doublet of epithelial cells from distal to PCT
    'Bcells': 'B cell',
    'Epi (Mes)': 'epithelial cell',
    'CD-IC-B': 'cell',  # Context required for a detailed classification
    'Technical/muscle (PCT)': 'muscle cell',
    'Technical/muscle (Imm)': 'muscle cell',
    'Macrophages': 'macrophage',
    'Epithelial (EC)': 'epithelial cell',
    'Epithelial (Imm)': 'epithelial cell',
    'Mito-rich Int': 'cell',  # Possibly referring to mitochondrial-rich cells from the intestine
    'PCT-S3-1': 'kidney cell',
    'Mito-rich (Imm)': 'cell',  # Possibly referring to mitochondrial-rich immune cells
    'EC(Imm)': 'endothelial cell'}


def get_coarser_map():
    
    coarser_cell_mapping_ = {
    "Nervous System": ['glial cell', 
                       'neuron', 
                       'neuroglial cell', 
                       'neural stem cell', 
                       'neuroendocrine cell',
                       'neural crest cell'],
    
    "Immune System (Other)": ['immune cell', 
                      'natural killer cell', 
                      'microglial cell', 
                      'dendritic cell', 
                      'plasma cell', 
                      'myeloid cell',
                      'innate lymphoid cell', 
                      'antigen-presenting cell', 
                      'lymphocyte'],
    
    "Connective Tissue (Other)": [ 'adipocyte',
                          'smooth muscle cell', 
                          'mesenchymal cell', 
                          'mesothelial cell',
                          'pericyte',
                          'connective tissue cell',
                          'trophoblast', 
                          'trophoblast cell'],
    
    "Cardiovascular": ['endothelial cell', 
                       'cardiomyocyte', 
                       'cardiac myocyte', 
                       'pericyte'],
    "General": ['cell',
               'interstitial cell'],
    "Epithelial": ['epithelial cell', 
                   'kidney epithelial cell', 
                   'enteroendocrine cell', 
                   'thymic epithelial cell', 
                   'lens cell',
                  'ependymal cell'],
    "Blood": ['blood cell', 'hematopoietic cell', 'neutrophil', 'eosinophil', 'megakaryocyte', 
              'mast cell', 'thymocyte'],
    "Stem and Progenitor": ['stem cell', 'progenitor cell', 'neural stem cell'],
    "Muscle": ['smooth muscle cell', 'muscle cell'],
    "Eye": ['retinal cell', 'photoreceptor cell'],
    "Kidney": ['kidney cell', 'podocyte'],
    "Digestive System": ['goblet cell', 'colon cell', 'enteroendocrine cell'],
    "Embryonic": ['germ cell', 
                  'trophoblast', 
                  'trophoblast cell'],
    "Tumor": ['tumor cell'],
    "Liver": ['hepatocyte'],
    "Macrophage": ['macrophage'],
    "Fibroblast": ['fibroblast'],
    'B cell':['B cell'],
    'T cell':['T cell'], 
    'Monocyte':['monocyte'], 
    'Endocrine':['endocrine cell']
    }

    coarser_cell_mapping = {}

    for key, values in coarser_cell_mapping_.items():
        for value in values:
            coarser_cell_mapping[value] = key
            
    return coarser_cell_mapping
